const { v4: uuidv4 } = require('uuid');
export const characterList = [{
        imageUrl: 'https://cdn.myanimelist.net/images/characters/6/288151.jpg',
        name: 'Rei',
        alt: 'An image of Rei from the anime Neon Genesis Evangelion.',
        id: 0,
        beenClicked: false,
        beenSelected: false,
      }, {
        imageUrl: 'https://cdn.myanimelist.net/images/characters/3/304983.jpg',
        name: 'Shinji',
        alt: 'An image of Shinji from the anime Neon Genesis Evangelion.',
        id: 1,
        beenClicked: false,
        beenSelected: false,
      }, {
        imageUrl: 'https://cdn.myanimelist.net/images/characters/15/447601.jpg',
        name: 'Misato',
        alt: 'An image of Misato from the anime Neon Genesis Evangelion.',
        id: 2,
        beenClicked: false,
        beenSelected: false,
      }, {
          imageUrl: 'https://cdn.myanimelist.net/images/characters/12/92452.jpg',
          name: 'Asuka',
          alt: 'An image of Asuka from the anime Neon Genesis Evangelion.',
          id: 3,
          beenClicked: false,
          beenSelected: false,
      }, {
          imageUrl: 'https://cdn.myanimelist.net/images/characters/13/145217.jpg',
          name: 'Kensuke',
          alt: 'An image of Kensuke from the anime Neon Genesis Evangelion.',
          id: 4,
          beenClicked: false,
          beenSelected: false,
      }, {
          imageUrl: 'https://cdn.myanimelist.net/images/characters/6/346978.jpg',
          name: 'Ritsuko',
          alt: 'An image of Ritsuko from the anime Neon Genesis Evangelion.',
          id: 5,
          beenClicked: false,
          beenSelected: false,
      }, {
          imageUrl: 'https://cdn.myanimelist.net/images/characters/10/145223.jpg',
          name: 'Kouzou',
          alt: 'An image of Kouzou from the anime Neon Genesis Evangelion.',
          id: 6,
          beenClicked: false,
          beenSelected: false,
      }, {
          imageUrl: 'https://cdn.myanimelist.net/images/characters/11/53131.jpg',
          name: 'Gendou',
          alt: 'An image of Gendou from the anime Neon Genesis Evangelion.',
          id: 7,
          beenClicked: false,
          beenSelected: false,
      }, {
          imageUrl: 'https://cdn.myanimelist.net/images/characters/15/60206.jpg',
          name: 'Ryouji',
          alt: 'An image of Ryouji from the anime Neon Genesis Evangelion.',
          id: 8,
          beenClicked: false,
          beenSelected: false,
      }, {
          imageUrl: 'https://cdn.myanimelist.net/images/characters/10/71728.jpg',
          name: 'Kaworu',
          alt: 'An image of Kaworu from the anime Neon Genesis Evangelion.',
          id: 9,
          beenClicked: false,
          beenSelected: false,
      }, {
          imageUrl: 'https://cdn.myanimelist.net/images/characters/7/346982.jpg',
          name: 'Pen Pen',
          alt: 'An image of Pen Pen from the anime Neon Genesis Evangelion.',
          id: 10,
          beenClicked: false,
          beenSelected: false,
      }, {
          imageUrl: 'https://cdn.myanimelist.net/images/characters/15/145219.jpg',
          name: 'Shigeru',
          alt: 'An image of Shigeru from the anime Neon Genesis Evangelion.',
          id: 11,
          beenClicked: false,
          beenSelected: false,
      }, {
        imageUrl: 'https://cdn.myanimelist.net/images/characters/4/346975.jpg',
        name: 'Naoko',
        alt: 'An image of Naoko from the anime Neon Genesis Evangelion.',
        id: 12,
        beenClicked: false,
        beenSelected: false,
    }, {
        imageUrl: 'https://cdn.myanimelist.net/images/characters/3/145215.jpg',
        name: 'Hikari',
        alt: 'An image of Hikari from the anime Neon Genesis Evangelion.',
        id: 13,
        beenClicked: false,
        beenSelected: false,
    }, {
        imageUrl: 'https://cdn.myanimelist.net/images/characters/4/290508.jpg',
        name: 'Makoto',
        alt: 'An image of Makoto from the anime Neon Genesis Evangelion.',
        id: 14,
        beenClicked: false,
        beenSelected: false,
    }, {
        imageUrl: 'https://cdn.myanimelist.net/images/characters/9/309031.jpg',
        name: 'Maya',
        alt: 'An image of Maya from the anime Neon Genesis Evangelion.',
        id: 15,
        beenClicked: false,
        beenSelected: false,
    }, {
        imageUrl: 'https://cdn.myanimelist.net/images/characters/15/276382.jpg',
        name: 'Touji',
        alt: 'An image of Touji from the anime Neon Genesis Evangelion.',
        id: 16,
        beenClicked: false,
        beenSelected: false,
    }, {
        imageUrl: 'https://cdn.myanimelist.net/images/characters/12/108140.jpg',
        name: 'Yui',
        alt: 'An image of Yui from the anime Neon Genesis Evangelion.',
        id: 17,
        beenClicked: false,
        beenSelected: false,
    },
]