const { v4: uuidv4 } = require('uuid');
export const characterList = [{
        imageUrl: 'https://cdn.myanimelist.net/images/characters/6/288151.jpg',
        name: 'Rei',
        alt: 'An image of Rei from the anime Neon Genesis Evangelion.',
        id: uuidv4(),
        beenClicked: false,
        beenSelected: true,
      }, {
        imageUrl: 'https://cdn.myanimelist.net/images/characters/3/304983.jpg',
        name: 'Shinji',
        alt: 'An image of Shinji from the anime Neon Genesis Evangelion.',
        id: uuidv4(),
        beenClicked: false,
        beenSelected: false,
      }, {
        imageUrl: 'https://cdn.myanimelist.net/images/characters/15/447601.jpg',
        name: 'Misato',
        alt: 'An image of Misato from the anime Neon Genesis Evangelion.',
        id: uuidv4(),
        beenClicked: false,
        beenSelected: true,
      }, {
          imageUrl: 'https://cdn.myanimelist.net/images/characters/12/92452.jpg',
          name: 'Asuka',
          alt: 'An image of Asuka from the anime Neon Genesis Evangelion.',
          id: uuidv4(),
          beenClicked: false,
          beenSelected: false,
      }, {
          imageUrl: 'https://cdn.myanimelist.net/images/characters/13/145217.jpg',
          name: 'Kensuke',
          alt: 'An image of Kensuke from the anime Neon Genesis Evangelion.',
          id: uuidv4(),
          beenClicked: false,
          beenSelected: false,
      }, {
          imageUrl: 'https://cdn.myanimelist.net/images/characters/6/346978.jpg',
          name: 'Ritsuko',
          alt: 'An image of Ritsuko from the anime Neon Genesis Evangelion.',
          id: uuidv4(),
          beenClicked: false,
          beenSelected: false,
      }, {
          imageUrl: 'https://cdn.myanimelist.net/images/characters/10/145223.jpg',
          name: 'Kouzou',
          alt: 'An image of Kouzou from the anime Neon Genesis Evangelion.',
          id: uuidv4(),
          beenClicked: false,
          beenSelected: false,
      }, {
          imageUrl: 'https://cdn.myanimelist.net/images/characters/11/53131.jpg',
          name: 'Gendou',
          alt: 'An image of Gendou from the anime Neon Genesis Evangelion.',
          id: uuidv4(),
          beenClicked: false,
          beenSelected: false,
      }, {
          imageUrl: 'https://cdn.myanimelist.net/images/characters/15/60206.jpg',
          name: 'Ryouji',
          alt: 'An image of Ryouji from the anime Neon Genesis Evangelion.',
          id: uuidv4(),
          beenClicked: false,
          beenSelected: false,
      }, {
          imageUrl: 'https://cdn.myanimelist.net/images/characters/10/71728.jpg',
          name: 'Kaworu',
          alt: 'An image of Kaworu from the anime Neon Genesis Evangelion.',
          id: uuidv4(),
          beenClicked: false,
          beenSelected: false,
      }, {
          imageUrl: 'https://cdn.myanimelist.net/images/characters/7/346982.jpg',
          name: 'Pen Pen',
          alt: 'An image of Pen Pen from the anime Neon Genesis Evangelion.',
          id: uuidv4(),
          beenClicked: false,
          beenSelected: false,
      }, {
          imageUrl: 'https://cdn.myanimelist.net/images/characters/15/145219.jpg',
          name: 'Shigeru',
          alt: 'An image of Shigeru from the anime Neon Genesis Evangelion.',
          id: uuidv4(),
          beenClicked: false,
          beenSelected: false,
      },
]